title: Lit Logits
author: Karanraj Chauhan

repository:
  url: https://github.com/chauhankaranraj/lit-logits

html:
  use_repository_button: true
  use_issues_button: true

execute:
  execute_notebooks: force

# # Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib
